% use the data generated by GetData and SplineInterpolation
integral = zeros(size(xs));  % create vector of correct size

% perform a numerical integration by adding the contributions
% use a trapezoidal integration
for k = 2:length(xs)
    integral(k) = integral(k-1) + (xs(k)-xs(k-1))*(ys(k-1)+ys(k))/2;
end%for
figure(3); axis(axislimits)
           plot(xs,ys,xs,integral)
           legend('function','intgeral')
